Repository LACE-Team/lace-repo, pull requests merged in 2018-12, with the labels that each got.

#149 WIP Selected MPP
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/components/FacebookFeed.js
  client/src/components/Feed.js
  client/src/components/Footer.js
  client/src/components/SMData.js
  client/src/components/SelectedMpp.js
  client/src/components/TwitterFeed.js
  client/src/components/dashComponents/SpeechFeed.js
  client/src/components/dashComponents/VotingRecords.js
  client/yarn.lock
Labels: enhancement

#150 More style
  client/package.json
  client/public/index.html
  client/src/components/Footer.js
  client/src/components/SelectedMpp.js
  client/src/components/dashComponents/FollowButton.js
  client/src/components/dashComponents/Mppinfo.js
  client/src/components/styling/semantic.css
  client/yarn.lock
Labels: enhancement

#152 fixed conflict
  client/src/components/Footer.js
  client/src/components/dashComponents/FollowButton.js
  client/src/components/dashComponents/Mppinfo.js
Labels: enhancement

#161 Moved event page to events tabs
  client/src/App.css
  client/src/App.js
  client/src/components/GenDash.js
  client/src/components/SMData.js
  client/src/components/UserDash.js
  client/src/components/dashComponents/EventFeed.js
  client/src/components/dashComponents/SelectMenu.js
Labels: Feature, enhancement

#162 facebook links are dynamic
  client/src/actions/index.js
  client/src/actions/types.js
  client/src/components/AuthButton.js
  client/src/components/FacebookFeed.js
  client/src/components/SMData.js
  client/src/components/SelectedMpp.js
  client/src/reducers/index.js
  client/src/reducers/nameReducer.js
Labels: enhancement

#167 fixed the following id screen
  client/src/components/Autocomplete.js
  client/src/components/dashComponents/EventFeed.js
Labels: bug

#171 Fixed some stuff
  -remove/AllMPPS.js
  -remove/FacebookFeed.js
  -remove/Landing.js
  -remove/Login.js
  -remove/SearchBar.js
  -remove/SelectedDash.js
  -remove/Signup.js
  -remove/TwitterFeed.js
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/components/Appbar.js
  client/src/components/AuthButton.js
  client/src/components/Footer.js
  client/src/components/SelectedMpp.js
  client/src/components/TwitterFeed.js
  client/src/components/dashComponents/EventFeed.js
  client/src/components/list/mppSocial.js
  client/src/utils/API.js
  client/yarn.lock
  package.json
  routes/mppRoutes.js
  yarn.lock
Labels: bug
